name: Nightly Acceptance
on:
  schedule:
    - cron: '0 5 * * *' # UTC

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
      - run: make test
        env:
          PACKER_ACC: ${{ secrets.PACKER_ACC }}
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}